application:
  security:
    token-prefix: "Bearer "
    jwt:
      secret:
      token-validity-in-seconds: 86400 # 24 hour
      token-validity-in-seconds-for-remember-me: 2592000
    oauth2:
      authorizedRedirectUris: http://localhost:3000/oauth2/redirect, myandroidapp://oauth2/redirect, myiosapp://oauth2/redirect


spring:
  application:
    name: Blog
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: phuong1580@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
#      hibernate.id.new_generator_mappings: true
#      hibernate.cache.use_second_level_cache: false
#      hibernate.cache.use_query_cache: false
#      hibernate.generate_statistics: true
  security:
    oauth2:
      client:
        registration:
            google:
              client-id:
              client-secret:
              redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
              scope:
                - email
                - profile
#            facebook:
#              client-id:
#              client-secret:
#              redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#              scope:
#                - email
#                - public_profile
#            github:
#              client-id:
#              client-secret:
#              redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#              scope:
#                - user:email
#                - read:user
        provider:
          facebook:
            authorization-uri: https://www.facebook.com/v3.0/dialog/oauth
            token-uri: https://graph.facebook.com/v3.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)